from django.urls import path 
from .views import (UserRegistrationView, login, PasswordResetRequestView, PasswordResetView, ShopUpdateView, SaleCreateView, 
                    ShopItemDetailView, ShopItemsByCategoryView, InventoryAnalysisView, chatbot_view, add_new_product_view,
                    ShopSalesListView, ShopSalesForDayView, ShopSalesForWeekView, ShopSalesForMonthView, ShopSalesForYearView,
                    ItemCreateView, ShopListView, UserShopsListView, ShopItemsListView, RestockCreateView, ShopRestocksListView,
                    RegisterShopView, UserAccountUpdateView, UserListView, UserDetailView, UserProfileDetailView)

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='user-registration'),
    path('login/', login, name='login'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('reset-password/<uidb64>/<token>/', PasswordResetView.as_view(), name='password_reset'),
    path('account/update/', UserAccountUpdateView.as_view(), name='user-account-update'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<uuid:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/<uuid:user_id>/profile/', UserProfileDetailView.as_view(), name='user-profile-detail'),
    path('users/<uuid:user_id>/shops/', UserShopsListView.as_view(), name='user-shops-list'),
    path('shops/register/<uuid:user_id>/', RegisterShopView.as_view(), name='register-shop'),
    path('shops/update/<uuid:pk>/', ShopUpdateView.as_view(), name='update-shop'),
    path('shops/update/<uuid:pk>/<uuid:user_id>/', ShopUpdateView.as_view(), name='update-shop'),
    path('items/create/<uuid:shop_id>/<uuid:user_id>/', ItemCreateView.as_view(), name='create-item'),
    path('shops/<uuid:shop_id>/item/<uuid:user_id>/<uuid:item_id>/', ShopItemDetailView.as_view(), name='shop-item-detail'),
    path('shops/', ShopListView.as_view(), name='shop-list'),
    path('shops/<uuid:shop_id>/items/<uuid:user_id>/', ShopItemsListView.as_view(), name='shop-items-list'),
    path('shops/<uuid:shop_id>/restock/<uuid:user_id>/<uuid:item_id>/', RestockCreateView.as_view(), name='restock-create'),
    path('shops/<uuid:shop_id>/restocks/<uuid:user_id>/', ShopRestocksListView.as_view(), name='shop-restocks-list'),
    path('shops/<uuid:shop_id>/sales/<uuid:user_id>/<uuid:item_id>/', SaleCreateView.as_view(), name='sale-create'),
    path('shops/<uuid:shop_id>/sales/<uuid:user_id>/', ShopSalesListView.as_view(), name='shop-sales-list'),
    path('shops/<uuid:shop_id>/sales/day/<uuid:user_id>/', ShopSalesForDayView.as_view(), name='shop-sales-for-day'),
    path('shops/<uuid:shop_id>/sales/week/<uuid:user_id>/', ShopSalesForWeekView.as_view(), name='shop-sales-for-week'),
    path('shops/<uuid:shop_id>/sales/month/<uuid:user_id>/', ShopSalesForMonthView.as_view(), name='shop-sales-for-month'),
    path('shops/<uuid:shop_id>/sales/year/<uuid:user_id>/', ShopSalesForYearView.as_view(), name='shop-sales-for-year'),
    path('shops/<uuid:shop_id>/items/<uuid:user_id>/categories/', ShopItemsByCategoryView.as_view(), name='shop-items-by-category'),
    path('shops/<uuid:shop_id>/inventory-analysis/<uuid:user_id>/', InventoryAnalysisView.as_view(), name='inventory-analysis'),
    path('chatbot/<uuid:shop_id>/<uuid:item_id>/<uuid:user_id>/', chatbot_view, name='chatbot_with_item'),
    path('chatbot/<uuid:shop_id>/<uuid:user_id>/', chatbot_view, name='chatbot'),
    path('new/<uuid:shop_id>/<uuid:user_id>/', add_new_product_view, name='add_new_product'),
]