# Generated by Django 4.2.6 on 2024-12-31 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(help_text="Name of the product.", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the product.", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product as sold by the shop.",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, help_text="Stock quantity available in the shop."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, max_length=500, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="oye.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shop_name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("landmark", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("service", "Service"),
                            ("manufacturing", "Manufacturing"),
                        ],
                        default="retail",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "operating_hours",
                    models.CharField(
                        blank=True,
                        help_text="Days and times the shop is open (e.g., Mon-Fri: 9am-5pm)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_of_employees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of employees in the shop",
                        null=True,
                    ),
                ),
                (
                    "business_registration_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Upload the business registration certificate if applicable",
                        null=True,
                        upload_to="registration_certificates/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload the shop's logo or image for branding",
                        null=True,
                        upload_to="shop_logos/",
                    ),
                ),
                (
                    "tax_identification_number",
                    models.CharField(
                        blank=True,
                        help_text="Tax Identification Number (TIN) for compliance",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True,
                        help_text="Bank details for financial transactions like payouts",
                        null=True,
                    ),
                ),
                (
                    "terms_and_conditions_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the owner has agreed to the terms and conditions",
                    ),
                ),
                (
                    "privacy_policy_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the owner has agreed to the privacy policy",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="oye.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Quantity of items restocked."),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price of the restocked items.",
                        max_digits=10,
                    ),
                ),
                ("restocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restocks",
                        to="oye.item",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restocks",
                        to="oye.shop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="oye.shop",
            ),
        ),
    ]
