# Generated by Django 4.2.6 on 2025-01-06 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0003_alter_item_options_shop_is_active_alter_item_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
