# Generated by Django 4.2.6 on 2025-01-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Item"},
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the Item.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(help_text="Name of the Item.", max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the Item as sold by the shop.",
                max_digits=10,
            ),
        ),
    ]
