# Generated by Django 4.2.6 on 2025-01-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0006_category_alter_item_options_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("grocery", "Grocery"),
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("furniture", "Furniture"),
                    ("appliances", "Appliances"),
                    ("books", "Books"),
                    ("stationery", "Stationery"),
                    ("toys", "Toys"),
                    ("beauty", "Beauty"),
                    ("health", "Health"),
                    ("pharmacy", "Pharmacy"),
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("services", "Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
