# Generated by Django 4.2.6 on 2025-01-29 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0007_alter_item_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        8, message="Password must be at least 8 characters long."
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, message="Password must not exceed 100 characters."
                    ),
                ],
            ),
        ),
    ]
