# Generated by Django 4.2.6 on 2025-01-29 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0008_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="warehouse",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
