# Generated by Django 4.2.6 on 2025-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0009_remove_item_warehouse_delete_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cost price of the Item.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Selling price of the Item.",
                max_digits=10,
            ),
        ),
    ]
