# Generated by Django 4.2.6 on 2025-02-01 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oye", "0011_remove_item_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="business_registration_certificate",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="logo",
        ),
    ]
